// import type { Metadata } from "next";
// import { Geist, Geist_Mono, Montserrat } from "next/font/google";
// import "./globals.css";
//
// import { ToastContainer } from "react-toastify";
// import "react-toastify/dist/ReactToastify.css";
//
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const montserrat = Montserrat({
//   variable: "--font-montserrat",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
//
// export const metadata: Metadata = {
//   title: "Service Link",
//   description: "Generated by create next app",
// };
//
// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${montserrat.variable} ${geistMono.variable} h-full antialiased`}
//       suppressHydrationWarning // <-- Fixed here
//     >
//       <body
//         className="min-h-full flex flex-col"
//         suppressHydrationWarning /* <-- Fixed here */
//       >
//         {children}
//         <ToastContainer position="top-right" />
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Providers from "@/store/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Service Link",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html
          lang="en"
          className={`${geistSans.variable} ${montserrat.variable} ${geistMono.variable} h-full antialiased`}
          suppressHydrationWarning
      >
      <body
          className="min-h-full flex flex-col"
          suppressHydrationWarning
      >
      <Providers>
        {children}
        <ToastContainer position="top-right" />
      </Providers>
      </body>
      </html>
  );
}